#schema BOOKKEEPER
#dictionary
	ACCOUNT_ID
	PARENT_ID
	ACCOUNT_NUMBER
	ACCOUNT_NAME
	ACCOUNT_TYPE
	DESCRIPTION
	CREATED_AT
	UPDATED_AT
	TRANSACTION_ID
	TRANSACTION_DATE
	REFERENCE_NUMBER
	ENTRY_ID
	AMOUNT
	ENTRY_TYPE
	BASE_CURRENCY_ID
	CURRENCY_ID
	CURRENCY_CODE
	CURRENCY_SYMBOL
	CURRENCY_NAME
	DECIMAL_PLACES
	EXCHANGE_RATE
	RATE_ID
	EFFECTIVE_DATE
#dictionary end
#file	ACCOUNTS
	ACCOUNT_ID
	PARENT_ID
	CURRENCY_ID
	ACCOUNT_NUMBER
	ACCOUNT_NAME
	ACCOUNT_TYPE
	DESCRIPTION
	CREATED_AT
	UPDATED_AT
#file end
#file	TRANSACTIONS
	TRANSACTION_ID
	BASE_CURRENCY_ID
	TRANSACTION_DATE
	DESCRIPTION
	REFERENCE_NUMBER
	CREATED_AT
	UPDATED_AT
#file end
#file	JOURNAL
	ENTRY_ID
	TRANSACTION_ID
	ACCOUNT_ID
	CURRENCY_ID
	AMOUNT
	EXCHANGE_RATE
	ENTRY_TYPE
	CREATED_AT
#file end
#file	CURRENCIES
	CURRENCY_ID
	CURRENCY_CODE
	CURRENCY_SYMBOL
	CURRENCY_NAME
	DECIMAL_PLACES
#file end
#file	EXCHANGERATES
	RATE_ID
	CURRENCY_ID
	BASE_CURRENCY_ID
	EXCHANGE_RATE
	EFFECTIVE_DATE
#file end
#key	CURRENCIES	CURRENCY_ID
#key	ACCOUNTS	ACCOUNT_ID
#key	TRANSACTIONS	TRANSACTION_ID
#key	JOURNAL	ENTRY_ID
key	EXCHANGERATES	RATE_ID
#schema end	BOOKKEEPER
